- hosts : localhost
  connection : local
  become: true

  tasks:
  - name : Install nginx
    apt:
      name: nginx
  - name: Starting nginx
  service:
    name: nginx
    state: started
  - name: nginx is enabled
  service:
    name: nginx
    enabled: yes
  - name: Remove former conf file
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent
  - name: writing conf file
  ansible.builtin.copy:
    src: /home/ubuntu/test-ansible/conf_files/default
    dest: /etc/nginx/sites-available/
    follow: yes
  - name: nginx is restarted
  service:
    name: nginx
    state: restarted
