- hosts : web_proxy
  connection : local
  remote_user: ubuntu
  become: true

  tasks:
  - name : Install nginx
    apt:
      name: nginx
  - name: Starting nginx
    service:
      name: nginx
      state: started
  - name: Nginx is enabled
    service:
      name: nginx
      enabled: yes
  - name: Remove former conf file
    ansible.builtin.file:
      path: /etc/nginx/sites-available/default
      state: absent
  - name: Writing conf file
    ansible.builtin.copy:
      src: /home/jhul/test-ansible/conf_files/default
      dest: /etc/nginx/sites-available/
      follow: yes
  - name: Nginx is restarted
    service:
      name: nginx
      state: restarted

 
