version: '3.3'
services:
  web1:
    build: ./app1
    image: app1_image
    container_name: app1
    restart: unless-stopped
    ports:
      - 3000:3000
  web2:
    build: ./app2
    image: app2_image
    container_name: app2
    restart: unless-stopped
    ports:
      - 3001:3001
  web3:
    build: ./app3
    image: app3_image
    container_name: app3
    restart: unless-stopped
    ports:
      - 3002:3002



